# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('0', 'answered'), ('1', 'unanswered'), ('2', 'pending')], default=1, max_length=11),
        ),
        migrations.AlterField(
            model_name='requestans',
            name='status',
            field=models.CharField(choices=[('0', 'answered'), ('1', 'unanswered'), ('2', 'pending')], default=1, max_length=11),
        ),
    ]
