# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_auto_20180328_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=74)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Waiting for student'), (2, 'Ongoing')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='categories.Category')),
                ('user_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_student', to=settings.AUTH_USER_MODEL)),
                ('user_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
