# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_auto_20180328_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Waiting'), (2, 'Pending'), (3, 'Ongoing')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_pool', to='categories.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_pool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
