# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpool',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (1, 'Waiting'), (2, 'Pending')], default=0),
        ),
    ]
