# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='text',
        ),
    ]
